# Generated by Django 4.2.5 on 2023-09-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='uer',
            new_name='user',
        ),
    ]
